services:
  db:
    image: postgres:15-alpine
    container_name: flathunter_db
    restart: always
    environment:
      POSTGRES_USER: hunter
      POSTGRES_PASSWORD: hunter_password
      POSTGRES_DB: flathunter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    container_name: flathunter_bot
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db


volumes:
  pgdata:

