services:
  db:
    image: postgres:15-alpine
    container_name: flathunter_db
    restart: always
    environment:
      POSTGRES_USER: hunter
      POSTGRES_PASSWORD: hunter_password
      POSTGRES_DB: flathunter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: flathunter_redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: flathunt_worker
    restart: always
    command: celery -A celery_app worker --pool=threads --concurrency=4 --loglevel=info
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    container_name: flathunter_beat
    restart: always
    command: celery -A celery_app beat --loglevel=info
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  bot:
    build: .
    container_name: flathunter_bot
    restart: always
    command: python bot/bot.py
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - cadvisor

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    restart: unless-stopped
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg
    command:
      - --docker_only=true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev/disk:/dev/disk:ro
    restart: unless-stopped

volumes:
  pgdata:
  prometheus_data:
  grafana_data: